apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: amazilo/expensy-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          value: mongodb://root:example@mongo:27017
        - name: REDIS_PASSWORD
          value: someredispassword
