apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: amazilo/devops-expensy-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/expensy
            - name: REDIS_URL
              value: redis://redis-leader:6379
            - name: NODE_ENV
              value: production

