apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000         # Port frontend will use to connect
      targetPort: 8706   # Actual container port
  type: ClusterIP
